### ISSUE TITLE
Sistem za preporuku knjiga

### ISSUE THREAD

**Issue by nemanja97** [ftn-ai-lab/ori-2019-siit#11]
**Članovi tima:**

- Kristina Đereg, SW36-2016, Grupa 3
- Nemanja Janković, SW52-2016, Grupa 2

**Asistenti:**

- Dragan Vidaković
- Ivana Zeljković

**Problem koji se rešava:**
Predlaganje sličnih knjiga za čitanje na osnovu prethodno unetog dela ili više njih.
Osnovne informacije o knjigama kao i njihove ocene dobićemo korišćenjem podataka iz dole navedenog dataset-a.
U osnovne informacije spadaju naziv knjige, autor, godina u koja je napisana i slično. Knjige su ocenjene brojevima od 1-5. Takođe, pored podataka o ocenama nekog korisnika, u obzir ćemo uzimati i listu knjiga koje želi pročitati. 
Ostale informacije, kao što su žanr knjige, period u kojem se najčešće čita dobićemo scrapeovanjem podataka sa sajta Goodreads.

**Algoritam:**
Content based filtering - https://en.wikipedia.org/wiki/Recommender_system#Content-based_filtering
Collaborative filtering - https://en.wikipedia.org/wiki/Collaborative_filtering

**Podaci koji se koriste:**
goodbooks-10k - https://github.com/zygmuntz/goodbooks-10k

**Metrika za merenje performansi:**

- Root Mean Square Error (RMSE)
- Neka od Top-N accuracy metrika

**Validacija rešenja:**
Poređenje RMSE rezultata sa rezultatima ostalih algoritama sistema preporuka.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by kristinadj** [comment]
https://github.com/ori2019-bookrecommendations/projekat
