### ISSUE TITLE
Analiza sentimenata ruskih tvitova

### ISSUE THREAD

**Issue by Marieta3** [ftn-ai-lab/ori-2019-siit#12]
- Članovi tima
    - 
    - Marieta Rakoš SW-43/2016, grupa 3

- Asistent
    -
    - Dragan Vidaković

- Problem koji se rešava
    -
    - Analiza sentimenata tvitova na ruskom jeziku uz pomoć neuronskih mreža. 
    - Od preuzetih podataka uzeće se veći deo za treniranje, a ostatak će se koristiti za testiranje.
    - Pre same analize, potrebno je tvit propustiti kroz predprocesiranje: tokenizacija, uklanjanje suvišnih reči, karaktera koji nisu slova, zamena slova "ё" slovom "e", stemming-svođenje reči na osnovni oblik (npr. imenice u nominativu) itd
   - Za stemming koristiću biblioteku RussianStemmer koja je sadržana u nltk biblioteci
    - Zatim sledi obučavanje i nakon toga testiranje i verifikacija
    - Cilj je da performanse algoritma na skupu za treniranje i test skupu budu što sličnije, ne bi bilo dobro da imamo jako dobre performanse na skupu za obučavanje i mnogo lošije performanse na test skupu
    - Prilikom obučavanja, puni se vokabular mreže. Potrebno je ograničiti taj vokabular na recimo 5000 reči i time odstraniti reči koje se ne sreću često, jer mreža ne zna dovoljno o njima da bi ih pravilno ocenila kao pozitivne odnosno negativne. Ove reči nisu od koristi.

- Algoritam
    -
    - Neuronske mreže
    - Naive Bayes - služi za poređenje preformansi
    - Neki zanimljiviji algoritam ukoliko pronađem (npr. SVM)

- Podaci koji se koriste
    -
    - http://study.mokoron.com/
    - Na ovom linku se mogu naći dva CSV fajla, jedan sa pozitivnim, drugi sa negativnim tvitovima na ruskom jeziku

- Metrika za merenje performansi
    -
    - Tačnost klasifikacije (accuracy), odnosno koliko puta neuronska mreža uspešno klasifikuje dati tvit kao pozitivan ili negativan

- Validacija rešenja
    -
    - Poređenje performansi sa rezultatima Naive Bayes algoritma
    - Poređenje performansi sa performansama postojećih algoritama koji se mogu pronaći na internetu

<a href="https://github.com/Marieta3/sentiment-analysis-russian">repozitorijum</a>

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
