### ISSUE TITLE
Klasterovanje finansijske aktive

### ISSUE THREAD

**Issue by DusanStevic** [ftn-ai-lab/ori-2019-siit#13]
- **Članovi tima:**
    -
    - Dušan Stević SW-10/2016, grupa 3
- **Asistent:**
    -
    - Dragan Vidaković
- **Problem koji se rešava:**
    -
    - Klasterovanje [finansijske aktive](https://www.investopedia.com/terms/f/financialasset.asp) (akcije, obveznice, menice, kripto valute, itd.) upotrebom različitih algoritama za klasterovanje.
    - Podaci o istorijskom kretanju cena finansijske aktive se prikupljaju sa različitih berzi i formira se [pool finansijskih sredstava](https://en.wikipedia.org/wiki/Pooling_(resource_management)).
   - Formirani portfolio sadrži različite tipove finansijske aktive (akcije, obveznice, kripto valute) koje potiču sa različitih tržišta ([NYSE](https://www.nyse.com/index), [Börse Frankfurt](http://www.boerse-frankfurt.de), [London Stock Exchange](https://www.londonstockexchange.com/home/homepage.htm)) i iz različitih privrednih grana (IT industrija, petrohemija, prehrambena industrija, telekomunikacije, autoindustrija, itd.).
   - Finansijski podaci sa berzi organizovani su u formi berzanskih izveštaja. Svaki berzanski izveštaj sadrži 6 standardnih kolona (open, close, high, low, volume, market capitalization). Ove kolone berzanskih izveštaja će se koristiti kao dimenzije po kojima će se vršiti klasterovanje.
   - Pre sprovođenja klasterovanja neophodno je prikupljene podatke pretprocesirati. Pretprocesiranje obuhvata:
        - Filtriranje podataka (odstranjivanje outlier-a).
        - Normalizaciju podataka (dimenzije volume i market capitalization se mere u milionima, dok se open, close, high, low dimenzije najčešće mere u stotinama i hiljadama).
   - Određivanje optimalnog K.
   - Klasterovanje pretprocesiranih podataka različitim algoritmima za klasterovanje.
   - Vizuelizacija dobijenih klastera.
   - Komparativna analiza dobijenih rezultata primenom različitih algoritama za klasterovanje.
   - Tumačenje dobijenih klastera kako bi se donela ispravna investiciona odluka. U fokusu je racionalni donosioca odluka koji treba da strukturira investicioni portfolio u skladu sa sopstvenim averzijama prema riziku.
   - Na osnovu sprovedenog istraživanja doneti zaključak kako je [tržište segmentirano](https://en.wikipedia.org/wiki/Market_basket).
 
- **Algoritam**
    - 
    - Algoritmi za određivanje optimalnog K:
        - [Elbow method](https://en.wikipedia.org/wiki/Elbow_method_(clustering))
    - Algoritmi za klasterovanje:
        - [K-means](https://en.wikipedia.org/wiki/K-means_clustering)
        - [DBSCAN](https://en.wikipedia.org/wiki/DBSCAN)
- **Podaci koji se koriste**
    -
    - [https://finance.yahoo.com](https://finance.yahoo.com)
    - [https://www.kaggle.com/qks1lver/amex-nyse-nasdaq-stock-histories](https://www.kaggle.com/qks1lver/amex-nyse-nasdaq-stock-histories)
    - [https://www.kaggle.com/albala/ticks-bitcoin-ethereumlitecoin-ripple](https://www.kaggle.com/albala/ticks-bitcoin-ethereumlitecoin-ripple)
    - [https://www.kaggle.com/dgawlik/nyse](https://www.kaggle.com/dgawlik/nyse)
    - [http://www.boerse-frankfurt.de](http://www.boerse-frankfurt.de)
    - [https://www.londonstockexchange.com/home/homepage.htm](https://www.londonstockexchange.com/home/homepage.htm)
- **Metrika za merenje performansi**
    -
    - [Silhouette Coefficient](https://en.wikipedia.org/wiki/Silhouette_(clustering))
- **Validacija rešenja**
    -
    - Empirijska validacija rešenja obuhvata ispitivanje da li su dobijeni rezultati klasterovanja u skaldu sa teorijom diverzifikacije:
        - Prostorno klasterovanje (finansijska aktiva koja potiče sa istog tržišta pripada istom klasteru)
        - Tipsko klasterovanje (isti tip finansijske aktive pripada istom klasteru)
        - Sektorsko klasterovanje (finansijska aktiva iz istog privrednog sektora pripada istom klasteru)
        - Klasterovanje prema prinosu (finansijska aktiva koja ima sličan prinos nalazi se u istom klasteru)
        - Klasterovanje prema volatilnosti  (finansijska aktiva koja ima sličan rizik nalazi se u istom klasteru)
        - Klasterovanje prema korelisanosti (pozitivno ili negativno korelisana finansijska aktiva nalazi se u istom klasteru)

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by DusanStevic** [comment]
https://github.com/DusanStevic/Klasterovanje-finansijske-aktive.git
