### ISSUE TITLE
Ucenje Agenta da igra Mortal Kombat 3 za Genesis konzolu

### ISSUE THREAD

**Issue by Veljko97** [ftn-ai-lab/ori-2019-siit#14]
### **Clanovi Tima:**
Veljko Vucenic SW59/2016, 3 Grupa

### **Asistent:**
Dragan Vidaković

### **Problem koji se resava:**
Poducavanje agenta da pobedjuje u igri Mortal Kombad 3 pod ogranicenjem koriscenja odredjenog karaktera za igru.

### **Algoritmi:**
NEAT - NeuroEvolution of Augmenting Topologies
Ucenje Uslovljavanjnem - mozda nece biti implementirano zbog hardverskog ogranicenja

### **Metrika za merenje performansi:**
Pobeda nad pobednikom

### **Validacija resenja:**
Broj pobeda na razlicitim tezinama i protiv razlicitih protivnika

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by Veljko97** [comment]
Link ka git repozitorijumu: https://github.com/Veljko97/ORI-2019-NEAT-MortalKombat3
