### ISSUE TITLE
Klasifikacija slika voća

### ISSUE THREAD

**Issue by Sava555** [ftn-ai-lab/ori-2019-siit#15]
Članovi tima:
Sava Katić SW25/2016, III grupa

Asistent:
Dragan Vidaković

Problem koji se rešava:
Klasifikacija slika voća u određene klase. Slike su labelirane.

Algoritam:
Konvolucione neuronske mreže

Dataset:
https://www.kaggle.com/moltean/fruits (podskup od 15 klasa)

Metrika za merenje performansi:
Kao glavna metrika koristiće se tačnost (_accuracy_) odnosno procenat uspešno klasifikovanih slika.

Validacija rešenja:
Trening skup: 75%
Validacini skup: 15%
Test skup: 10%

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by Sava555** [comment]
Repo: https://github.com/Sava555/klasifikacija-voca
