### ISSUE TITLE
Anime recommendation

### ISSUE THREAD

**Issue by Pejicic** [ftn-ai-lab/ori-2019-siit#16]
Članovi tima:
Jelena Pejičić SW35/2015, V grupa

Asistenti:
Ivana Zeljković

Problem koji se rješava:
Predlaganje anima koji bi se mogli svidjeti korisniku, uzimajući u obzir korisnike slične njemu. Pod sličnim korisnicima se misli na one koju su gledali iste anime i dali im slične ocjene. 

Algoritam:
Prvo će se uraditi neki vid pretprocesiranja podataka, kako bi uklonili korisnike koji su ocijenili mali broj anima, kao i one koji su ih ocjenjivali jednolično (sve istim ocjenama ).
Pristup Collaborative filtering će biti korišćen, kao i Content based filtering, te će se porediti rješenja dobijena različitim pristupima.

Dataset:
Koristiće se podaci sa sajta myanimelist.net . Ti podaci se sastoje od dva csv fajla. U prvom fajlu su podaci o samoj animi, poput njenog identifikatora, imena, žanra, prosječne ocjene i slično. U drugom fajlu se nalazi identifikator korisnika, identifikator anime i ocjena koju je korisnik dao animi.

Metrika za merenje performansi:
RMSE (Root Mean Square Error)

Validacija rešenja:
Porediću  dobijene RMSE moja dva pristupa i RMSE odgovarajućeg algoritma dobijen pomoću pythonove biblioteke surprise, koja služi za izgradnju i analiziranje sistema preporuke

Github
https://github.com/Pejicic/AnimeRecommendation

**Comment by ivanazeljkovic** [comment]
Tema je u redu, međutim navedeni pristup nije dovoljno kompleksan. 
Neophodno je proširiti prijavu projekta još jednim pristupom (algoritmom), čija će se uspešnost porediti sa navedenim.
Za dopunu prijave imate rok od 24h, dok će u suprotnom predlog projekta biti odbijen.

**Comment by Pejicic** [comment]
Proširila sam prijavu i Content based filteringom, te ću kao što ste rekli porediti rezultate sa prvim pristupom. I ukoliko je u redu dobijene RMSE porediću sa ugrađenim algoritmima u surprise biblioteci kako bih validirala svoje rješenje.

**Comment by ivanazeljkovic** [comment]
Tema je odobrena.
Neophodno je ostaviti link ka GitHub repozitorijumu projekta.
Srećno sa radom.
