### ISSUE TITLE
Obučavanje RL agenta za Chrome Dinosaur Game

### ISSUE THREAD

**Issue by fivkovic** [ftn-ai-lab/ori-2019-siit#18]
## Članovi tima
Filip Ivković, SW33/2016, 4. Grupa
## Asistent
Ivana Zeljković
## Problem koji se rešava
Obučavanje reinforcement learning agenta koji igra Chrome Dinosaur Game. Implementacija algoritama koji bi agenta doveli do inteligentnog ponašanja u vidu prevazilaženja prepreka i maksimizovanja ukupnog skora.

Originalna verzija igre je relativno kompleksna, iz razloga što je brzina agenta varijabilna (_povećava se tokom vremena_) i postoji više tipova prepreka koji se pojavljuju na nasumičnim mestima. Kako bi učenje ovih stvari zahtevalo duži vremenski period i unelo neželjeni šum (_u slučaju oblaka koji nemaju direktan uticaj na agenta_), okruženje će biti uprošćeno i ograničeno na konstantnu brzinu kako bi se skratio proces obučavanja agenta.

Kao okruženje za igru, biće iskorišćena javno dostupna implementacija [igre](https://github.com/shivamshekhar/Chrome-T-Rex-Rush) kreirana pomoću Python 3 i [pygame](https://github.com/pygame/) biblioteke.

## Algoritam/algoritmi
Algoritmi koji će se koristiti prilikom rešavanja problema su:
- Q-Learning (_osnovni pristup_)
- Approximate Q-Learning
- Genetski algoritam

Kao feature-i za opis stanja biće korišćeni:
- Udaljenost od sledeće prepreke
- Dimenzije prepreke
- Relativna brzina prepreke u odnosu na agenta
- Stanje agenta (_da li je trenutno u skoku, padu ili sagnut_)

Odabir ovih feature-a podstaknut je [radom](http://cs229.stanford.edu/proj2016/report/KeZhaoWei-AIForChromeOfflineDinosaurGame-report.pdf) koji se bavi sličnim problemom. U toku implementacije i testiranja rešenja biće razmotreno i uvođenje novih feature-a sa ciljem postizanja boljih rezultata.

## Metrika za merenje performansi
Broj pređenih prepreka i ukupan skor agenta.

## Validacija rešenja
Poređenje prosečnih i maksimalnih skorova prosečnog ljudskog igrača i agenta za navedene algoritme, na nivou 25 igara kao i poređenje dobijenih rezultata sa rezultatima različitih pristupa relevantnih radova koji su se bavili istim problemom. Dodatno će biti priložen i video snimak koji pokazuje scenarije treniranja i testiranja, kao i demonstracija rešenja na odbrani projekta.

## Repozitorijum
https://github.com/fivkovic/ori-projekat

**Comment by ivanazeljkovic** [comment]
Tema je odobrena.
Neophodno je ostaviti link ka GitHub repozitorijumu projekta.
Srećno sa radom.
