### ISSUE TITLE
Klasifikacija raka kože

### ISSUE THREAD

**Issue by fmladenovic** [ftn-ai-lab/ori-2019-siit#2]
**Članovi tima:**
Filip Mladenović sw-11/2016, IV grupa 

**Asistent:**
Ivana Zeljković

**Problem koji se rešava:**
Problem je klasifikacija slika. Svrstavanje slika, po svojim karakteristikama, u određene skupove koji su prethodno labelirani. 

**Algoritam:**
Konvoluciona neuronska mreža sa DenseNet arhitekturom.

**Skupovi podataka:**
HAM10000 - [https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DBW86T](url)
PH^2 - [https://www.dropbox.com/s/k88qukc20ljnbuo/PH2Dataset.rar](url)

**Metrika za merenje performansi:**
Kao glavna metrika će se koristiti tačnost (_accuracy_).

**Validacija rešenja:**
Trening skup: 70%
Validacini skup: 15%
Test skup: 15%

**Comment by ivanazeljkovic** [comment]
Tema je odobrena.
Neophodno je ostaviti link ka GitHub repozitorijumu projekta.
Srećno sa radom.

**Comment by fmladenovic** [comment]
Link: https://github.com/FilipMeng/cnn-cancer-classifier
