### ISSUE TITLE
FIFA 19 - predviđanje pozicije fudbalera na osnovu vrednosti atributa

### ISSUE THREAD

**Issue by UrosOgrizovic** [ftn-ai-lab/ori-2019-siit#4]
**Članovi tima:** 
Uroš Ogrizović, SW-39/16, grupa 4

**Asistent:** 
Ivana Zeljković

**Problem koji se rešava:**
U pitanju je klasifikacija. Konkretnije, treba predvideti poziciju fudbalera u video igri FIFA 19 na osnovu vrednosti atributa za tog igrača. Biće potrebno enkodovati kategorička obeležja, kao i izvršiti redukciju dimenzionalnosti, tj. _feature selection_.

**Algoritam:**
Naivni Bajesov klasifikator, SVM klasifikator, ...

**Skup podataka:**
https://www.kaggle.com/karangadiya/fifa19/discussion

**Metrika za merenje performansi:**
 Kao glavna metrika će se koristiti tačnost (_accuracy_).

**Validacija rešenja:**
Trening skup: 70%
Validacini skup: 15%
Test skup: 15%

**Repozitorijum:**
https://github.com/UrosOgrizovic/FIFA-19-player-position-predictor

**Comment by ivanazeljkovic** [comment]
Tema je odobrena.
Neophodno je ostaviti link ka GitHub repozitorijumu projekta.
Srećno sa radom.
