### ISSUE TITLE
Obučavanje Flappy Bird agenta koristeći obični Q-Learning i Monte Carlo Q-learning

### ISSUE THREAD

**Issue by NikolaZubic** [ftn-ai-lab/ori-2019-siit#9]
- **Članovi tima**
Nikola Zubić, SW-03/2016, Grupa 2

- **Asistent**
Ivana Zeljković

- **Problem koji se rješava**
Korišćenje Q-Learning i Monte Carlo Q-learning algoritama za obučavanje "Flappy Bird" agenta tako da on maksimizuje svoj skor. Cilj agenta je da uspješno prolazi između gornje i donje cijevi. Upoređuju se performanse dva agenta, a koristi se PyGame Learning Environment: https://pygame-learning-environment.readthedocs.io/en/latest/ .
Igra je ograničena na 30fps. Skup akcija čini akcija akceleracije agenta ka gore.
Terminalno stanje igre nastaje ako agent napravi kontakt sa zemljom ili gornjom/donjom cijevi.
Za svaku cijev koju prođe, agent dobija nagradu u iznosu od +1, a ako stigne u terminalno stanje dobija negativnu nagradu (kaznu) u iznosu od -1.

- **Algoritmi**
Q-Learning, Monte Carlo Q-learning.

- **Metrika za mjerenje performansi**
Porediće se rezultati oba pristupa i varirati faktor eksploracije i faktor učenja kako bi se vidjelo kako se mijenjaju performanse u skladu sa njima. Cilj je posmatrati i kako se mijenja nagrada kroz epohe treniranja. Onaj agent koji postiže iz epohe u epohu veću nagradu će reći koji agent bolje igra ovu igru. Kroz PLE okruženje moguće je modelovati i rastojanje između gornje i donje cijevi (u razumnom opsegu; da nisu cijevi previše blizu jedna drugoj) i to isto možemo uzeti u obzir kao faktor prilikom eksperimentisanja, te i drugi varijabilni faktori koje nudi okruženje će se koristiti prilikom istraživanja problema.

- **Validacija rješenja**
Porediće se performanse sa performansama koje su ostvarili eksperti u ovoj igri, kako bi se vidjelo kako ovi algoritmi kotiraju sa ljudima koji su među najboljima u ovoj igri. Takođe, github projekti koji se tiču Flappy Bird Q-learning-a i Monte Carlo Q-learning-a  koje budem našao, njihove performanse ću isto uporediti sa svojim. Naravno, potrebno je da se u tom projektu razmatraju metrike kao i moje, kao primjer za poređenje može se uzeti: https://github.com/chncyhn/flappybird-qlearning-bot .

**Comment by ivanazeljkovic** [comment]
Tema je odobrena.
Neophodno je ostaviti link ka GitHub repozitorijumu projekta.
Srećno sa radom.

**Comment by NikolaZubic** [comment]
> Tema je odobrena.
> Neophodno je ostaviti link ka GitHub repozitorijumu projekta.
> Srećno sa radom.

https://github.com/reinai/FlappyBirdAI

**Comment by NikolaZubic** [comment]
SARSA uči akcije prema politici koju prati dok Q learning to radi relativno u odnosu na epsilon greedy, pa je zato ovaj pristup izbačen jer se svedu u suštini na isto, u početku SARSA daje bolje rezultate, a kasnije na isto konvergiraju. Zato je uzet Monte Carlo Q learning jer se dobijaju znatno drugačiji rezultati.
